### ISSUE TITLE
公式戦出場試合数＋GA数を配信するbotを作成する

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/FotBot#26]
細かすぎて伝わらないマンシティの方のツイートの反響が大きいかつ手動っぽいので、
正しいデータ基盤であるstatsbombから取得してスクリプトで型を作ってlambdaで配信する。
https://twitter.com/city_pic/status/1632026229439340544

**Comment by gundogan8** [comment]
👆の方はメモ帳で書いてスクショしているのでFW～GKまで一発で見れる。
スレッド機能で実装すると見栄えはよくなくなるけれど、DFとGKのGA数は期待していないと思うので、
いったんはFＷ、MF、DF、GKに分けてやってみよう。
ちょっと寂しそうなので出場試合数等も追加でつけてみるのもあり。

**Comment by gundogan8** [comment]
以前作成したcityzensと同じ実装形態なので挑戦的な実装ではない。確実にニーズがあるかどうか分からないのが少し不安。
発信者の方がフォロワー数４万人なので僕のフォロワーに需要があるかどうかはびみょい。

**Comment by gundogan8** [comment]
イメージ
```
2022-23 (EPL / UEFA / FA / Carabao / CS)

FW
ハーランド　👕40⚽×33 👟×5
アルバレス　👕40 ⚽×10 👟×3
マフレズ　👕40 ⚽×12👟×6
```
↓
```
2022-23 (EPL / UEFA / FA / Carabao / CS)

MF
デブライネ　👕40⚽×33 👟×5
フォーデン　👕40 ⚽×10 👟×3
ギュンドアン　👕40 ⚽×12👟×6
...
```
以下同じく対応してみる。目標は投稿言い値数の平均10。

**Comment by gundogan8** [comment]
ポジションごとに配信するのか。GA数順に配信するのか。
テストしながら考えてみる。
https://fbref.com/en/squads/b8fd03ef/2022-2023/all_comps/Manchester-City-Stats-All-Competitions

**Comment by gundogan8** [comment]
やはり、これ手動でやっておられるのかミスってはる。チャンスやな。
https://twitter.com/city_pic/status/1632026988268646400

**Comment by gundogan8** [comment]
ImportError: lxml not found, please install it
 クソ開発環境からかよマジで怠いんご

**Comment by gundogan8** [comment]
毎日30分とかでやってこ
https://github.com/gundogan8/FotBot/blob/main/code/ga/main.ipynb

**Comment by gundogan8** [comment]
これデータを画像出力して配信できると強い。。。
まじで作ってみたいんご

**Comment by gundogan8** [comment]
確実ではないけれど需要はあるはず。。。一気に作ってみるか。。。どうしよ。。。作ろう

**Comment by gundogan8** [comment]
やっぱり手動っぽいな。これ自動化しよう。色々書いたけどまずはＭＶＰでやろう。
配信した時の見え方が重要やからスレッドにするとはいえ、小さくまずは作ってみよう。
基盤ができたら、あとはスタバで作業すればおつりがくるやろ
https://twitter.com/city_pic/status/1642162617820274691?s=20

**Comment by ikmz0104** [comment]
上手くいってるように見えて、
最後のスレッドがうまく機能していない。なんとかしないとな
https://twitter.com/gundogan_vamos/status/1644200199743754240

**Comment by ikmz0104** [comment]
また次回試そう。セインツ戦で変わるやろうし。
```
else:
                sled_count += 1
                print('sled_count', sled_count)
                
                # スレッド処理を実施
                if match_count_in_sled == match_count:
                    res = _tweetBot(text, tweetID)
                    print('スレッド処理でツイート成功!', res)
                
                # 最終スレッド処理を実施
                last_sled_flag = len(df) - MAX_PLAYER_INFO - match_count_in_sled * MAX_PLAYER_INFO
                print('len(df)', len(df))
                print('sled_count', sled_count)
                print('MAX_PLAYER_INFO', MAX_PLAYER_INFO)
                print('match_count_in_sled * MAX_PLAYER_INFO', match_count_in_sled * MAX_PLAYER_INFO)
                if last_sled_flag == match_count:
                    res = _tweetBot(text, tweetID)
                    print('スレッド処理でツイート成功!', res)
                else:
                    print('stay...match_count', match_count)
                    print('stay...text', text)
```

**Comment by ikmz0104** [comment]
別タスクカナ
