### ISSUE TITLE
最終スレッドがツイートされない

### ISSUE THREAD

**Issue by ikmz0104** [ikmz0104/FotBot#34]
# 状況
成績報告ツイートの最終スレッドがツイートできない。（情報は取得できているが、ロジックが上手く効いていない）
https://twitter.com/gundogan_vamos/status/1644200199743754240

<img width="278" alt="image" src="https://user-images.githubusercontent.com/74099733/230752431-ab937c65-6b9f-4d5f-a3af-2ecb6d3e75b2.png">
↑
本来はここにも下記４名の成績がスレッド投稿されるのに、ツイートされない
<img width="326" alt="image" src="https://user-images.githubusercontent.com/74099733/230752466-05cff3ef-b91d-4187-828c-e04b2135b166.png">

**Comment by ikmz0104** [comment]
データ基盤はこちら

**Comment by ikmz0104** [comment]
それらをツイートに載せる実装がこちら

**Comment by ikmz0104** [comment]
実行関数
```
tweetBot.createTweetMsg(df)
```

**Comment by MotoKoikeKeiba** [comment]
```  python
def createTweetMsg(df: pd.DataFrame):
    match_count = 0
    tweetID = ''

    for index, row in df.iterrows():
        match_count += 1
        
        # 試合カードが5試合たまった場合
        if match_count >= MAX_PLAYER_INFO:
            # ツイートする
            tweetID = _tweetBot(text, tweetID)
            # マッチカウントを初期化
            match_count = 0

    if match_count > 0:
        # ツイートする
        tweetID = _tweetBot(text, tweetID)
```

私ならシンプルにこんなイメージで書きますね。

**Comment by ikmz0104** [comment]
神様仏様元小池様、エジルのスルーパスのようです。
ちょっと動かしてみます。

**Comment by ikmz0104** [comment]
"errorMessage": "400 Bad Request\nYour Tweet text is too long. For more information on how Twitter determines text length see https://github.com/twitter/twitter-text.",

**Comment by MotoKoikeKeiba** [comment]
メッセージが長すぎるようなので、
`MAX_PLAYER_INFO`をチューニングしてください。

**Comment by ikmz0104** [comment]
MAX_PLAYER_INFO= 3等にしましたがうまく動かずでした、いったん今日は終了します！
<img width="462" alt="image" src="https://user-images.githubusercontent.com/74099733/230778565-2bf0c817-f936-4f35-a287-a9356b9edc16.png">

**Comment by MotoKoikeKeiba** [comment]
400エラーは、文字数超過であるはずです。
エラー内容が違って、403エラーとかになるのであれば、同じツイートは、API経由ではNGとなります。

今回は、テストなので、2回目のツイートとなりエラーとなっているかと推察します。

**Comment by ikmz0104** [comment]
改修完了なり！！！！
https://twitter.com/gundogan_vamos/status/1688546890504425472
